default['pkg_server'] = "http://10.164.91.13/files/PYTHON/"
default['python_pkg'] = "Python-3.3.3.tar.xz"
default['python_tarball'] = "Python-3.3.3.tar"
default['python_setup'] = "setuptools-25.1.2.tar.gz"
default['pip'] = "get-pip.py"
default['pip_whl'] = "pip-8.1.2-py2.py3-none-any.whl"
default['pip_wheel'] = "wheel-0.29.0-py2.py3-none-any.whl"
